apiVersion: v1 #string
kind: Pod #string
metadata: # dectionary
  name: myapp-pod
  labels: #dictinary
    app: myapp-pod
spec:
  containers: #list
    - name: myapp 
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
